mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import handler404 , handler500
from groups import views as core_views

urlpatterns = [
	path('',include('post.urls')),
	path('',include('groups.urls')),
	path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('settings/', core_views.settings, name='settings'),
    path('settings/password/', core_views.password, name='password'),
]

handler404 = 'groups.views.error_404_view'
handler500 = 'groups.views.error_500_view'

post/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from .views import (
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
	UserListView,
	GListView
)
from . import views as views
from django.conf.urls.static import static


urlpatterns = [
	path('', views.index, name='index'),
	path('result/', views.searchposts, name='searchposts'),
	path('profile/', views.view_profile, name='view_profile'),
	path('profile/update/', views.edit_profile, name='edit_profile'),
	path('profile/edit/', views.edit_basic_profile, name='edit_basic_profile'),
	path('register/', views.register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='post/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='post/logout.html'), name='logout'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('user/<str:username>', UserListView.as_view(), name = 'user-posts'),
	path('groups/<str:name>', GListView.as_view(), name = 'group-posts'),
	path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
	path('account/reset_password', views.ResetPasswordRequestView.as_view(), name="reset_password"),
	path('account/reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(),name='reset_password_confirm'),
	path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from groups.models import Com
from django.db.models.signals import post_save
from imagekit.models.fields import ProcessedImageField , ImageSpecField
from imagekit.processors import ResizeToFill

User._meta.get_field('email')._unique = True

# Create your models here.


class Posts(models.Model):
	title = models.CharField(max_length = 100)
	context = models.TextField()
	date_posted = models.DateTimeField(default = timezone.now)
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	groups = models.ForeignKey(Com, on_delete = models.CASCADE)
	image = models.ImageField(upload_to='post_images', blank=True)

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})
	def __str__(self):
		return self.title


class Comment(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    bio = models.CharField(max_length=100, default='',blank = True)
    website = models.URLField(default='',blank = True)
    phone = models.CharField( max_length=15, blank=True) # validators should be a list
    #image = models.ImageField(upload_to='profile_image',default = 'octocat.png')
    image = ProcessedImageField(default="octocat.png", upload_to='profile_image',processors=[ResizeToFill(200,200)], format='JPEG', options={'quality': 90})
    thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(50, 50)],format='JPEG',options={'quality': 100})

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)

post/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Comment
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    class Meta:
        model = User
        fields = ( 'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    image = forms.ImageField(required=True)
    class Meta:
        model = UserProfile
        fields = (
            'bio',
            'phone',
            'website',
            'image',
        )

class EditBasicProfileForm(UserChangeForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Posts
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from groups.models import Com
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.contrib.auth import login ,get_user_model
from .tokens import account_activation_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage , send_mail
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView,
	FormView,
)
from django.contrib.auth.decorators import login_required
from django import forms
from django.template import loader
from django.contrib.auth.tokens import default_token_generator
from django.db.models import Q
from .forms import UserRegisterForm, EditProfileForm, EditBasicProfileForm, CommentForm ,PasswordResetRequestForm
from django.core.paginator import Paginator
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


def index(request):
	posts = Posts.objects.all().order_by('-date_posted')
	groups = Com.objects.all()
	paginator = Paginator(posts, 10)
	page = request.GET.get('page')
	posts = paginator.get_page(page)
	return render(request,'post/index.html', {'posts': posts , 'groups':groups})

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Posts, id=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('post-detail', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'post/add_comment_to_post.html', {'form': form})


def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			# user.is_active = False
			user.save()
			# current_site = get_current_site(request)
			# mail_subject = 'Activate your blog account.'
			# message = render_to_string('acc_active_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid':urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token':account_activation_token.make_token(user),
            # })
			# to_email = form.cleaned_data.get('email')
			# email = EmailMessage(mail_subject, message, to=[to_email])
			# email.send()
			# username = form.cleaned_data.get('username')
			# messages.success(request, f'Account created for {username}!')
			# messages.info(request, f'Please confirm your email address to complete the registration')
			# return render(request,'email.html', {'to_email': to_email})
			return redirect('index')
	else:
		form = UserRegisterForm()
	return render(request, 'post/register.html', {'form': form })

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, f'Thank you for your email confirmation. Now you can login your account. {user}!')
    else:
        messages.success(request, f'Activation link is invalid!')
    return redirect('index')

@login_required
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'post/profile.html', args)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST,request.FILES, instance=request.user.userprofile)

        if form.is_valid():
            form.save()
            return redirect('view_profile')
    else:
        form = EditProfileForm(instance=request.user.userprofile)
        args = {'form': form}
        return render(request, 'post/update_profile.html', args)

@login_required
def edit_basic_profile(request):
    if request.method == 'POST':
        form = EditBasicProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('view_profile')
    else:
        form = EditBasicProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'post/edit_profile.html', args)



class PostListView(ListView):
	model = Posts
	template_name = 'post/index.html'
	context_object_name = 'posts'
	ordering = ['-date_posted']

class UserListView(ListView):
	model = Posts
	template_name = 'post/user_posts.html'
	context_object_name = 'posts'
	ordering = ['-date_posted']

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		return Posts.objects.filter(user=user).order_by('-date_posted')

class GListView(ListView):
	model = Posts, Com
	template_name = 'groups/group_posts.html'
	context_object_name = 'posts'

	def get_context_data(self, **kwargs):
		name = get_object_or_404(Com, name=self.kwargs.get('name'))
		context = super(GListView, self).get_context_data(**kwargs)
		context['groups'] = Com.objects.filter(name = name)
		return context

	def get_queryset(self):
		name = get_object_or_404(Com, name=self.kwargs.get('name'))
		return Posts.objects.filter(groups=name).order_by('-date_posted')



class PostDetailView(DetailView):
	model = Posts


class PostCreateView(LoginRequiredMixin, CreateView):
	model = Posts
	fields = ['groups','title', 'context','image']
	def form_valid(self, form):
		title = form.cleaned_data.get('title')
		group = form.cleaned_data.get('groups')
		obj = Com.objects.filter(name=group)
		val = obj.first().count
		val+=1
		obj.update(count=val)
		messages.success(self.request, f'Post with title {title} Created!')
		form.instance.user = self.request.user
		return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Posts
	fields = ['title', 'context','image']
	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.user:
			return True
		return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Posts
	success_url = '/'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.user:
			return True
		return False

def searchposts(request):
    if request.method == 'GET':
        query= request.GET.get('q')
        submitbutton= request.GET.get('submit')
        if query is not None:
            lookups= Q(title__icontains=query) | Q(context__icontains=query)
            results= Posts.objects.filter(lookups).distinct()
            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'post/search.html', context)

        else:
            return render(request, 'post/search.html')

    else:
        return render(request, 'post/search.html')


DEFAULT_FROM_EMAIL = "saibaaskar24091999@gmail.com"
class ResetPasswordRequestView(FormView):
    template_name = "test_template.html"
    success_url = '/login'
    form_class = PasswordResetRequestForm

    @staticmethod
    def validate_email_address(email):
        try:
            validate_email(email)
            return True
        except ValidationError:
            return False

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            data= form.cleaned_data["email_or_username"]
        if self.validate_email_address(data) is True:
            associated_users= User.objects.filter(Q(email=data)|Q(username=data))
            if associated_users.exists():
                for user in associated_users:
                        c = {
                            'email': user.email,
                            'domain': request.META['HTTP_HOST'],
                            'site_name': 'VIIT Blog',
                            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                            'user': user,
                            'token': default_token_generator.make_token(user),
                            'protocol': 'http',
                            }
                        subject_template_name='password_reset_subject.txt'
                        email_template_name='password_reset_email.html'
                        subject = loader.render_to_string(subject_template_name, c)
                        subject = ''.join(subject.splitlines())
                        email = loader.render_to_string(email_template_name, c)
                        send_mail(subject, email, DEFAULT_FROM_EMAIL , [user.email], fail_silently=False)
                result = self.form_valid(form)
                messages.success(request, 'An email has been sent to ' + data +". Please check its inbox to continue reseting password.")
                return result
            result = self.form_invalid(form)
            messages.error(request, 'No user is associated with this email address')
            return result
        else:
            associated_users= User.objects.filter(username=data)
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': request.META['HTTP_HOST'],

templates/post/_pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo</a> </li>
        <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a> </li>
        {% endif %}
        {% for num in posts.paginator.page_range %}
        {% if posts.number == num %}
        <li class="page-item"><a class="page-link">{{ num }}</a></li>
        {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a> </li>
        {% endif %}
        {% endfor %}
        {% if posts.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>

</nav>

templates/post/add_comment_to_post.html
{% extends 'post/header.html' %}

{% block content %}
{{ form.errors}}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.text }}
        <button type="submit" class="save btn btn-default">ADD</button>
    </form>
{% endblock %}

templates/post/edit_profile.html
{% extends "post/header.html"%} {% block title %}Edit Profile{% endblock %} {% block content %}
<br>
<br>
<div class="container">
<center>
 <h3 class="text-primary" >Edit Profile</h3>
 </center>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        <center>
            <p> First Name {{ form.first_name }}</p>
            <p> Last Name : {{ form.last_name }} </p>
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="cancel" class="btn btn-outline-primary" onclick="window.location='/'">Cancel</button>
        </center>
    </form>

</div>
<!-- 
<div class="container">
        <div class="span3 well">
            <center>
                <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="{{ post.user.userprofile.thumbnail.url }}" name="aboutme" width="140" height="140" class="img-circle"></a>
                <h3>{{ user }}</h3>
                <em> Click on Image to see more</em>
            </center>
        </div> -->
<!-- Modal -->
<!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title" id="myModalLabel">More About {{ user }} </h4>
                    </div>
                    <div class="modal-body">
                        <center>
                            <img src="{{ post.user.userprofile.thumbnail.url }}" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
                            <h3 class="media-heading">{{ user }}</h3>
                            <span><strong>Skills: </strong></span>
                            <span class="label label-warning">HTML5/CSS</span>
                            <span class="label label-info">Adobe CS 5.5</span>
                            <span class="label label-info">Microsoft Office</span>
                            <span class="label label-success">Windows XP, Vista, 7</span>
                        </center>
                        <hr>
                        <center>
                            <p class="text-left"><strong>Bio: </strong><br> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem dui, tempor sit amet commodo a, vulputate vel tellus.</p>
                            <br>
                        </center>
                    </div>
                    <div class="modal-footer">
                        <center>
                            <button type="button" class="btn btn-default" data-dismiss="modal">I've heard enough about Joe</button>
                        </center>
                    </div>
                </div>
            </div>
        </div>
</div> -->

{% endblock content %}

templates/post/index.html
{% extends "post/header.html"%}
{% block title %}Vignan Blog Post{% endblock %}
{% block content %}

<div class="row">
<div class="d-none d-xl-block col">
<h2>Groups</h2>
                <ul class="list-group">
				{% for group in groups%}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                   <a href="{% url 'groups' %}{{ group.name }}"> {{group}} 
                    <span class="badge badge-primary badge-pill">{{ group.count }}</span> </a>
                </li>
				{% endfor %}
    		</ul>
</div>
<div class="col-xl-9">
</br>
{% for post in posts %}

<div class="card shadow p-3 mb-5 bg-white rounded">
	<div style="text-align: inline;">
		<img src="{{ post.user.userprofile.thumbnail.url }}" width="40" height="40" alt="Profile Image" style="border-radius: 50%;">
		&nbsp;
		<a class="card-subtitle mb-2 text-muted" href="{% url 'user-posts' post.user.username %}">{{ post.user }}</a>
	</div>

	<div class="card-body">
		<a class="card-title" style="font-size: 2em;" href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
		</br>
		<a href="{% url 'groups' %}{{ post.groups }}" class="pills">#{{ post.groups }}</a><br>
		<small>{{ post.date_posted|date:"F d, Y" }}</small>
		</br></br>
		<p class="card-text">{{ post.context|truncatewords:"30" }}</p>

	</div>
	<a href="{% url 'post-detail' post.id %}">Comments: {{ post.comments.count }}</a>
</div>

{% endfor %}

{% if posts.paginator.num_pages > 1 %}

<!-- start -->
{% include 'post/_pagination.html' with posts=posts %}
<!-- end -->

{% endif %}


</div>
<div class="d-none d-xl-block col">
<h2>Events</h2>
                <div class="card" >Events</div>
</div>
</div>
{% endblock content %}

templates/post/logout.html
{% extends "post/header.html" %}
{% block title %}Logout{% endblock %} 
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

templates/post/posts_confirm_delete.html
{% extends "post/header.html" %}
{% block title %}Confirm Delete post{% endblock %}
{% block content %}
<div class="content-section container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

templates/post/posts_detail.html
{% extends "post/header.html" %} {% block title %}{{ object.title }}{% endblock %} {% block content %}
<article class="media content-section container">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="article-title">{{ object.title }}</h2>
            {% if object.user == user %}
            <div>
                <a class="btn btn-outline-secondary" href="{% url 'post-update' object.id %}">Update</a>
                <a class="btn btn-outline-secondary" href="{% url 'post-delete' object.id %}">Delete</a>
            </div>
            {% endif %}
            <a href="{% url 'user-posts' object.user %}">{{ object.user }}</a>
            </br>
            <p class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>

        </div>
        {% if object.image %}
        <img src={{ object.image.url }} width="250px"> <br> {% endif %}
        <br>
        <p>{{ object.context}}</p>
    </div>
</article>



<div class="container">
    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'add_comment_to_post' object.id %}">Add comment</a><br> {% endif %} {% for comment in object.comments.all %}
    <br>
    <div class="row">
        <img src="{{ comment.author.userprofile.thumbnail.url }}" width="40" height="40" alt="Profile Image" style="border-radius: 50%;"> &nbsp;&nbsp;
        <div class="card border-left-0 border-right-0 border-top-0">
            <a class="card-subtitle font-weight-bold" href="{% url 'user-posts' comment.author %}">{{ comment.author }}</a>
            <div class="date text-muted">
                {{ comment.created_date }}
            </div>
            <strong>{{ comment.text|linebreaks }}</strong>
        </div>
    </div>
    {% empty %}
    <p>No comments here yet :(</p>
    {% endfor %}
</div>

{% endblock content %}

templates/post/register.html
{% extends "post/header.html"%}
{% block title %}Register{% endblock %}

{% block content %}
{% load widget_tweaks %}

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Register</h5>
                        {{ form.errors}}
                             {{ form.help_text }}
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                             <div class="form-label-group">
                             
                                {% render_field form.username placeholder=form.username.label class+="form-control"  %}
                                <label for="id_username">Username</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.email placeholder=form.email.label class+="form-control"  %}
                                <label for="id_email">Email</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.first_name placeholder=form.first_name.label class+="form-control"  %}
                                <label for="id_first_name">First Name</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.last_name placeholder=form.last_name.label class+="form-control"  %}
                                <label for="id_last_name">Last Name</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.password1 placeholder=form.password1.label class+="form-control"  %}
                                <label for="id_password1">Password</label>
                            </div>
                            <div class="form-label-group">
                                {% render_field form.password2 placeholder=form.password2.label class+="form-control"  %}
                                <label for="id_password2">Confirm Password</label>
                            </div>
                            <button class="btn btn-lg btn-primary btn-block text-uppercase"
                                type="submit">Register</button>
                            </form>
                            <hr class="my-4">
                            <a class="btn btn-lg rounded-pill btn-danger btn-block text-uppercase" href="{% url "social:begin" "google-oauth2" %}" > Sign up with Google</a>
                            <a class="btn btn-lg rounded-pill btn-dark btn-block text-uppercase" href="{% url "social:begin" "github" %}" > Sign up with GitHub</a>
                            <a class="btn btn-lg rounded-pill btn-primary btn-block text-uppercase" href="{% url "social:begin" "twitter" %}" > Sign up with Twitter</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>







<style>
    :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }

    body {


        background: #56CCF2;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #2F80ED, #56CCF2);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #2F80ED, #56CCF2); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

        
        background-size: cover;
        background-position: center;
    }

    .card-signin {
        border: 0;
        border-radius: 1rem;
        box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .card-signin .card-title {
        margin-bottom: 2rem;
        font-weight: 300;
        font-size: 1.5rem;
    }

    .card-signin .card-body {
        padding: 2rem;
    }

    .form-signin {
        width: 100%;
    }

    .form-signin .btn {
        font-size: 80%;
        border-radius: 5rem;
        letter-spacing: .1rem;
        font-weight: bold;
        padding: 1rem;
        transition: all 0.2s;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }

    .form-label-group>input,
    .form-label-group>label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }

    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }

    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }

    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-moz-placeholder {
        color: transparent;
    }

    .form-label-group input::placeholder {
        color: transparent;
    }

    .form-label-group input:not(:placeholder-shown) {
        padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);
    }

    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
    }

    .btn-google {
        color: white;
        background-color: #ea4335;
    }

    .btn-facebook {
        color: white;
        background-color: #3b5998;
    }

    /* Fallback for Edge
-------------------------------------------------- */

    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }

    /* Fallback for IE
-------------------------------------------------- */

    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }
</style>
{% endblock content %}